### PR TITLE
Only require fog-core

### PR DESCRIPTION
**Pull request by leifcr**
To lighten the gem dependencies, I changed the gemspec to only require fog-core, fog-json and fog-xml.

Any providers should be added in the app itself.

### CODE REVIEW

**Comment by leifcr** [comment]
@jnicklas Can I please ask for a merge on this?

**Comment by zjwhitehead** [comment]
Any reason why this hasnt been merged in yet?

**Comment by leifcr** [comment]
@zjwhitehead you can use the gem 'leifcr-refile-fog'
Add this to your gemfile (Or different providers if needed)
```
gem 'leifcr-refile-fog'
gem 'fog-rackspace'
```

Then add this to your refile initializer:
```
require 'refile/fog'
```

Settings for the various providers are still the same.

**Comment by sobrinho** [comment]
Thanks! <3

**Comment by leifcr** [comment]
Thanks for merging!

**Pull request merged**
